### ISSUE TITLE
sheet option 

### ISSUE THREAD

**Issue by pablett** [leonardoshibata/tab2xl2#1]
Thank you for the ado. 
I tried to use the sheet command and did not worked. Maybe I am not aware of the correct syntax. 
Can you orient me on how I can make it work?

Thanks

**Comment by leonardoshibata** [comment]
Hi pablett,

There is no _sheet_ option on tab2xl2, maybe you are confusing it with tab2xl (without the 2 at the end).

In tab2xl2 you use _using_.

Eg: 
`tab2xl2 _rowVariable_ _columnVariable_ using _filename_`

See if it works.

Best
